### ISSUE TITLE
一个小疑问

### ISSUE THREAD

**Issue by fuqiang03** [openwrt-develop/luci-theme-atmaterial#1]
![qq 20171107012514](https://user-images.githubusercontent.com/26851715/32454577-96651704-c35a-11e7-9709-14378929a899.png)
这个斜杠总是变多变少

**Comment by panda-mute** [comment]
@fuqiang03 Fix in commit:
ca5492b7071d2aa100b70b0bcda7b08d5fc16c77

Please take a test.

**Comment by fuqiang03** [comment]
我感觉能好看些
![qq 20180416150704](https://user-images.githubusercontent.com/26851715/38794549-113ba262-4188-11e8-9a93-1640c352c99d.png)
![qq 20180416150731](https://user-images.githubusercontent.com/26851715/38794550-1188b0e8-4188-11e8-89d5-53efb72490a7.png)

**Comment by panda-mute** [comment]
主题修改欢迎PR
