### ISSUE TITLE
请教一个额外的问题

### ISSUE THREAD

**Issue by fuqiang03** [openwrt-develop/luci-theme-atmaterial#2]
用路由器的重启页面，重启路由，在关掉dhcp后，同时要删除如下图的文件，重启完成后可正常返回到登入页面，开启dhcp后，不等路由器重启完成，直接进入主页页面，更换主题也是同样的情况，用4.4.126内核，软件包用的matter库，我应该怎么做，求解。
![qq 20180420215617](https://user-images.githubusercontent.com/26851715/39055008-aeca90aa-44e5-11e8-9e92-e95dfef26678.png)

**Comment by fuqiang03** [comment]
已经解决  当执行关机命令时候 会执行rc.d下面的文件

**Comment by panda-mute** [comment]
So, 到底怎么解决的？？？

**Comment by fuqiang03** [comment]
k15modem 这个文件可以删除 不影响使用（ 真心感觉光猫访问这个插件 好用）去掉stop=15 因为 系统在关机的时候 会执行 脚本的stop  如果手速够快可在关机的时候刷新日志 会发现 信息  所以在脚本stop中 尽量不要有dhcp 防火墙的重启指令
我的情况特殊还有另一个文件影响重启出错 上图中 有k14chinadns文件  他在stop添加 了 dhcp重启指令 这些也是在 日志中发现的  
我的临时办法是更换了 chinadsn的脚本(感觉chinadsn好像已经被人放弃了)

**Comment by fuqiang03** [comment]
大神遇到过wrt1900acs  5g无线宕机的情况吗
